@startuml
'https://plantuml.com/use-case-diagram
footer: App version: 0.1.0
left to right direction

:Maker: as maker

rectangle Printtables {

    package projects {
        (Register new project) as register_project
        (View project) as view_project
    }

    package inventory {
        (Manage assemblies) as manage_assembly
        (Manage parts) as manage_parts
    }

}

maker ---> register_project
maker ---> view_project
@enduml