name: Cross-compile

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os_name: Raspbian
            target: aarch64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1
      - name: Install Cross
        run: cargo install cross
      - name: Build binary for ${{ matrix.platform.os_name }}
        run: cross build --target ${{ matrix.platform.target }} --locked --release
